# Generated by Django 4.1.1 on 2022-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_stock', models.CharField(max_length=50)),
                ('book_price', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_year', models.BigIntegerField(default=0)),
                ('book_language', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_status', models.BigIntegerField(default=0)),
                ('book_desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
