# Generated by Django 4.1.1 on 2022-10-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('book_quantity', models.BigIntegerField(default=0)),
                ('book_price', models.BigIntegerField(default=0)),
                ('book_author', models.CharField(max_length=50)),
                ('book_year', models.BigIntegerField(default=0)),
                ('book_language', models.CharField(max_length=50)),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_status', models.BigIntegerField(default=0)),
                ('book_desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeapp.category', verbose_name='Category')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_books',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homeapp.category', verbose_name='Category'),
        ),
    ]
