# Generated by Django 4.1.1 on 2022-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_book_category_subcategory_delete_tbl_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_oldprice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='img2',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
    ]
